requires 'App::Cmd';
requires 'Text::Table';
requires 'Config::INI';
requires 'Data::Printer';
requires 'Capture::Tiny';
requires 'Net::Amazon::Route53';
requires 'Mouse';
requires 'Params::Validate';
requires 'Capture::Tiny';
